services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - ${REDIS_PORT}

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:
